//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace personelisTakip.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFirmalar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblFirmalar()
        {
            this.tbl_cagrilar = new HashSet<tbl_cagrilar>();
            this.tblmesajlar = new HashSet<tblmesajlar>();
            this.tblmesajlar1 = new HashSet<tblmesajlar>();
        }
    
        public int id { get; set; }
        public string ad { get; set; }
        public string yetki { get; set; }
        public string telefon { get; set; }
        public string mail { get; set; }
        public string sektor { get; set; }
        public string il { get; set; }
        public string ilce { get; set; }
        public string adres { get; set; }
        public string sifre { get; set; }
        public string gorsel { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_cagrilar> tbl_cagrilar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblmesajlar> tblmesajlar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblmesajlar> tblmesajlar1 { get; set; }
    }
}
