//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace personelisTakip.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblmesajlar
    {
        public int id { get; set; }
        public Nullable<int> gonderen { get; set; }
        public Nullable<int> alici { get; set; }
        public string konu { get; set; }
        public string mesaj { get; set; }
        public Nullable<System.DateTime> tarih { get; set; }
        public Nullable<bool> durum { get; set; }
    
        public virtual tblFirmalar tblFirmalar { get; set; }
        public virtual tblFirmalar tblFirmalar1 { get; set; }
    }
}
